en:
  greeting_message: "Hello! Here you can take a quiz and test your knowledge! To start, type /start_quiz. To change the language (currently available: ua and en), use /lang ua. Remember, you can navigate between questions using /c n, where n is the question number. To stop quiz use /stop. Good luck!"
  farewell_message: "Goodbye! See you soon"
  start: "Before navigating between questions, you need to start the quiz using /start_quiz"
  lang_change: "Language changed to %{code}"
  incorrect_lang: "Language %{e_code} is not available"
  unanswered_questions: "To finish the quiz, you must answer every question. Missing answers for question(s) №: %{numbers}"
  quiz_end: "Quiz finished. Results: \n%{res}"
  incorrect_lang_format: "Invalid language format, please enter exactly 2 characters"
  incorrect_c_format: "Invalid question number format, please enter a space and 1 number after /c"
  unknown_command: "Invalid command, please enter a valid command"
  question: "Question"
  press_button: "Please press one of the buttons below"
  false_question_num: "Invalid question number. Please enter between 1 and %{q_num}."
  report_message: "Correct: %{correct}, Incorrect: %{incorrect}, Success Rate: %{rate}%"
ua:
 greeting_message: "Привіт! Тут ти можеш пройти квіз та перевірити свої знання! Для того, щоб почати, введи /start_quiz. Для того, щоб змінити мову, (наразі доступна ua та en) використай /lang en. Пам'ятай, ти можеш переміщуватись між питаннями використовуючи /c n, де n номер питання. Для завершення квізу використай /stop. Удачі!"
 farewell_message: "Прощавай! До зустрічі"
 start: "Перед тим, як переміщуватись між питаннями, треба почати тест квіз через /start_quiz"
 lang_change: "Мову змінено на %{code}"
 incorrect_lang: "Мова %{e_code} недоступна"
 unanswered_questions: "Для того, щоб закінчити тест, треба відповісти на кожне питання. Немає відповіді на питання №: %{numbers}"
 quiz_end: "Квіз завершено. Результати: \n%{res}"
 incorrect_lang_format: "Неправильний формат мови, будь ласка, введіть лише 2 символи"
 incorrect_c_format: "Неправильний формат номера питання, будь ласка, введіть пробіл та 1 число після /c"
 unknown_command: "Команда невалідна, будь ласка введіть валідну команду"
 question: "Питання"
 press_button: "Будь ласка, натисність на одну з кнопок нижче"
 false_question_num: "Неправильний номер питання. Будь ласка, введіть число між 1 та %{q_num}."
 report_message: "Правильних відповідей: %{correct}, Неправильних: %{incorrect}, Успішність: %{rate}%"
