- question: Для чого використовуються нейронні мережі?
  answers:
    - Для розпізнавання образів, обробки мови та прийняття рішень.
    - Для збереження даних у базах даних.
    - Для ручного введення інформації користувачем.