- question: Що таке навчання з підкріпленням?
  answers:
    - Метод машинного навчання, де агент навчається шляхом взаємодії з середовищем і отримання винагороди або покарання.
    - Тип глибокої нейронної мережі.
    - Метод збору даних для тренування моделей.