- question: Що таке машинне навчання?
  answers:
    - Метод аналізу даних, який дозволяє комп’ютерам навчатися з досвіду без явного програмування.
    - Процес створення глибоких нейронних мереж.
    - Ручне програмування алгоритмів для обробки даних.