- question: Що таке глибоке навчання?
  answers:
    - Підгалузь машинного навчання, що використовує багатошарові нейронні мережі.
    - Техніка збору даних для статистичних досліджень.
    - Метод програмування на основі правил.