- question: Що таке перенавчання (overfitting) в машинному навчанні?
  answers:
    - Коли модель надто добре підлаштовується під навчальні дані, втрачаючи здатність узагальнювати.
    - Коли модель зовсім не навчається на даних.
    - Коли модель працює тільки на тестових даних.