- question: What are neural networks used for?
  answers:
    - For pattern recognition, language processing, and decision-making.
    - For storing data in databases.
    - For manual user data input.