- question: What is deep learning?
  answers:
    - A subfield of machine learning that uses multilayer neural networks.
    - A data collection technique for statistical research.
    - A rule-based programming method.